# Generated by Django 4.1.4 on 2023-01-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='curd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=80)),
                ('phone', models.IntegerField()),
                ('college', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='new',
        ),
    ]
